linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errorlint
    - revive
    - thelper
    - unconvert
    - whitespace
    - bodyclose
