builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./

nfpms:
  - id: goreleaser
    maintainer: Pete Wagner <deb@pwagner.net>
    formats:
      - deb
    contents:
      - src: debian/debcache.service
        dst: /etc/systemd/system/debcache.service
      - dst: /var/cache/debcache
        type: dir
        file_info:
          mode: 0700

dockers:
  - use: buildx
    dockerfile: Containerfile.goreleaser
    image_templates:
      - "ghcr.io/thepwagner-org/debcache:latest"
