before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./

archives:
  - format: binary

nfpms:
  - id: goreleaser
    maintainer: Pete Wagner <deb@pwagner.net>
    formats:
      - deb
