name: CI

on:
  push:
    branches: [ '**' ]
    tags-ignore: [ 'v*.*.*' ]

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/golang-test.yaml@renovate/golangci-golangci-lint-action-4.x
    permissions:
      contents: read
