name: Release

on:
  push:
    tags: [ 'v*.*.*' ]
    

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/golang-release.yaml@29fc277227ae3fc735e9ac7790d307f0516a70c3 # v3.0.0
    permissions:
      contents: write
    with:
      docker: true
    secrets:
      ghcr-token: ${{secrets.WAPWAGNER_TOKEN}}
