name: Release

on:
  push:
    tags: [ 'v*.*.*' ]
    

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/golang-release.yaml@7a8c48d526143c8b058cd97476f7fcea16deb674 # v2.9.0
    permissions:
      contents: write
    with:
      docker: true
    secrets:
      ghcr-token: ${{secrets.WAPWAGNER_TOKEN}}
