name: Release

on:
  push:
    tags: [ 'v*.*.*' ]
    

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/golang-release.yaml@254500a695fcc8d6c5253189e70f95699733841f # v2.11.0
    permissions:
      contents: write
    with:
      docker: true
    secrets:
      ghcr-token: ${{secrets.WAPWAGNER_TOKEN}}
