name: Release

on:
  push:
    tags: [ 'v*.*.*' ]
    

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/golang-release.yaml@16e79010b51bd1d6b7b247a59c70bee903e480e4 # v3.0.1
    permissions:
      contents: write
    with:
      docker: true
    secrets:
      ghcr-token: ${{secrets.WAPWAGNER_TOKEN}}
