name: Release

on:
  push:
    tags: [ 'v*.*.*' ]
    

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/golang-release.yaml@golang-release
    permissions:
      contents: read
      packages: write # TODO: why do i need this?
    with:
      docker: true
    secrets:
      token: ${{secrets.WAPWAGNER_TOKEN}}
